  maximum:
    length_email: 255
    length_name: 50
    group_function: 30
    group_description: 100
  minimum:
    length_pass: 6
  users:
    size_page: 50
    size_image: 60
    per_page: 10
    per_page_search_member: 5
  task_content: 60
